/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.anasoid.jmc.examples;

import org.anasoid.jmc.core.wrapper.jmeter.testelement.TestPlanWrapper;

public class App {


    public static void main(String[] args) {

        TestPlanWrapper testPlanWrapper = TestPlanWrapper.builder().build();
        //ApplicationTest applicationTest=new ApplicationTest();
    }
}
