# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & Test

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-main-V3-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-main-V3


      - name: printenv
        run: printenv

      - name: Java version
        run: java -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --stacktrace --refresh-dependencies --console=verbose  build


      - name: Publish artifact Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: '**/build/reports/**'
